name: Sync Image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: '请输入新的小版本号 (例如: 15.95.2)'
        required: true
        default: '15.95.2'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull, Tag and Push
        run: |
          # 1. 基础镜像名 (源)
          SRC="ghcr.io/${{ github.repository_owner }}/erpnext:v15"
          SRC=$(echo "$SRC" | tr '[:upper:]' '[:lower:]')
          
          # 2. 从手动输入中获取新版本号
          NEW_TAG="${{ github.event.inputs.version_tag }}"
          DEST="lvxj11/erpnext:${NEW_TAG}"
          
          echo "正在从 GHCR 拉取: $SRC"
          docker pull $SRC
          
          echo "正在打新标签: $DEST"
          docker tag $SRC $DEST
          docker tag $SRC lvxj11/erpnext:v15
          
          echo "推送中..."
          docker push $DEST
          docker push lvxj11/erpnext:v15
